# Generated by Django 4.0 on 2021-12-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_useranswers_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='submited',
            field=models.BooleanField(default=False),
        ),
    ]
